source:
  namespace: doid
  type: Disease
  label: Human Disease Ontology
  prefix: http://purl.obolibrary.org/obo/
target:
  namespace: ICD10
  type: Disease
  label: International Classification of Disease, Version 10
  prefix: 	https://identifiers.org/icd:
link:
  file: link.tsv
  forward:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  reverse:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
update:
  frequency:
  method: doid-icd10.sh